<h1>PALMER PENGUIN DATA ANALYTICS</h1>
<hr>
<h3>Biscocho, Leslianne R.</h3>
<h4>BSIT-3A</h4>

In [1]:
import numpy as np
import pandas as pd

<p>IMPORTING DATASET TO JUPYTER NOTEBOOK</p>
<p>Converting Dataset to Data Frame</p>
<ul><strong>REQUIREMENTS</strong>
    <li>Name of Data Frame</li>
    <li>Source</li>
</ul>

In [2]:
penguin = pd.read_csv('datasets\\penguins.csv')

In [3]:
penguin

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [4]:
penguin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
 7   year               344 non-null    int64
dtypes: float64(4), int64(1), object(3)
memory usage: 21.6+ KB

In [5]:
penguin.describe()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
count,342.000000,342.000000,342.000000,342.000000,344.000000
mean,43.921930,17.151170,200.915205,4201.754386,2008.029070
std,5.459584,1.974793,14.061714,801.954536,0.818356
min,32.100000,13.100000,172.000000,2700.000000,2007.000000
25%,39.225000,15.600000,190.000000,3550.000000,2007.000000
50%,44.450000,17.300000,197.000000,4050.000000,2008.000000
75%,48.500000,18.700000,213.000000,4750.000000,2009.000000
max,59.600000,21.500000,231.000000,6300.000000,2009.000000

In [6]:
penguin.describe().T

,count,mean,std,min,25%,50%,75%,max
bill_length_mm,342.0,43.921930,5.459584,32.1,39.225,44.45,48.5,59.6
bill_depth_mm,342.0,17.151170,1.974793,13.1,15.600,17.30,18.7,21.5
flipper_length_mm,342.0,200.915205,14.061714,172.0,190.000,197.00,213.0,231.0
body_mass_g,342.0,4201.754386,801.954536,2700.0,3550.000,4050.00,4750.0,6300.0
year,344.0,2008.029070,0.818356,2007.0,2007.000,2008.00,2009.0,2009.0

In [7]:
penguin.isnull()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,True,True,True,True,True,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
339,False,False,False,False,False,False,False,False
340,False,False,False,False,False,False,False,False
341,False,False,False,False,False,False,False,False
342,False,False,False,False,False,False,False,False
343,False,False,False,False,False,False,False,False

In [8]:
penguin.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [9]:
penguin['species'].unique()

array(['Adelie', 'Gentoo', 'Chinstrap'], dtype=object)

In [10]:
penguin['island']

0      Torgersen
1      Torgersen
2      Torgersen
3      Torgersen
4      Torgersen
         ...
339        Dream
340        Dream
341        Dream
342        Dream
343        Dream
Name: island, Length: 344, dtype: object

In [11]:
penguin['island']=='Dream'

0      False
1      False
2      False
3      False
4      False
       ...
339     True
340     True
341     True
342     True
343     True
Name: island, Length: 344, dtype: bool

In [12]:
Gentoo_df=penguin[penguin['species']=="Gentoo"]

In [13]:
Gentoo_df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
152,Gentoo,Biscoe,46.1,13.2,211.0,4500.0,female,2007
153,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,male,2007
154,Gentoo,Biscoe,48.7,14.1,210.0,4450.0,female,2007
155,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,male,2007
156,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,male,2007
...,...,...,...,...,...,...,...,...
271,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2009
272,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,female,2009
273,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,2009
274,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,2009
275,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,2009

In [14]:
Adelie_df=penguin[penguin['species']=="Adelie"]

In [15]:
Adelie_df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
147,Adelie,Dream,36.6,18.4,184.0,3475.0,female,2009
148,Adelie,Dream,36.0,17.8,195.0,3450.0,female,2009
149,Adelie,Dream,37.8,18.1,193.0,3750.0,male,2009
150,Adelie,Dream,36.0,17.1,187.0,3700.0,female,2009
151,Adelie,Dream,41.5,18.5,201.0,4000.0,male,2009

In [16]:
Chinstrap_df=penguin[penguin['species']=="Chinstrap"]

In [17]:
Chinstrap_df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
276,Chinstrap,Dream,46.5,17.9,192.0,3500.0,female,2007
277,Chinstrap,Dream,50.0,19.5,196.0,3900.0,male,2007
278,Chinstrap,Dream,51.3,19.2,193.0,3650.0,male,2007
279,Chinstrap,Dream,45.4,18.7,188.0,3525.0,female,2007
280,Chinstrap,Dream,52.7,19.8,197.0,3725.0,male,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

<h1><strong>How many penguins has the body mass of 4000kg?<strong></h1>

In [18]:
penguin['body_mass_g']>=4000

0      False
1      False
2      False
3      False
4      False
       ...
339     True
340    False
341    False
342     True
343    False
Name: body_mass_g, Length: 344, dtype: bool

In [19]:
(penguin['species']=="Chinstrap") & (penguin['body_mass_g']>=4000)

0      False
1      False
2      False
3      False
4      False
       ...
339     True
340    False
341    False
342     True
343    False
Length: 344, dtype: bool

In [20]:
Chinstrap_heavy=penguin[(penguin['species']=="Chinstrap") & (penguin['body_mass_g']>=4000)]

In [21]:
Chinstrap_heavy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 284 to 342
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            16 non-null     object
 1   island             16 non-null     object
 2   bill_length_mm     16 non-null     float64
 3   bill_depth_mm      16 non-null     float64
 4   flipper_length_mm  16 non-null     float64
 5   body_mass_g        16 non-null     float64
 6   sex                16 non-null     object
 7   year               16 non-null     int64
dtypes: float64(4), int64(1), object(3)
memory usage: 1.1+ KB

<h1><strong>How to Fillup Null Values?</strong></h1>

In [22]:
penguin.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [23]:
penguin['bill_length_mm'].fillna

<bound method NDFrame.fillna of 0      39.1
1      39.5
2      40.3
3       NaN
4      36.7
       ...
339    55.8
340    43.5
341    49.6
342    50.8
343    50.2
Name: bill_length_mm, Length: 344, dtype: float64>

In [24]:
penguin['bill_length_mm'].mean()

43.9219298245614

In [25]:
penguin['bill_length_mm']=penguin['bill_length_mm'].fillna(penguin['bill_length_mm'].mean())

In [26]:
penguin['bill_depth_mm']=penguin['bill_depth_mm'].fillna(penguin['bill_depth_mm'].mean())

In [27]:
penguin['flipper_length_mm']=penguin['flipper_length_mm'].fillna(penguin['flipper_length_mm'].mean())

In [28]:
penguin['body_mass_g']=penguin['body_mass_g'].fillna(penguin['body_mass_g'].mean())

In [29]:
penguin['sex']=penguin['sex'].fillna(penguin['sex'].mode()[0])

In [30]:
penguin.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
dtype: int64

<h1><strong>How to change the Datatype of a column?</strong></h1>

In [31]:
penguin['species']=penguin['species'].astype('category')
penguin['island']=penguin['island'].astype('category')
penguin['sex']=penguin['sex'].astype('category')
penguin['year']=penguin['year'].astype('category')

In [32]:
penguin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    category
 1   island             344 non-null    category
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    category
 7   year               344 non-null    category
dtypes: category(4), float64(4)
memory usage: 12.7 KB

<h1><strong>How to create a column?</strong></h1>

In [33]:
penguin.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex', 'year'],
      dtype='object')

In [34]:
penguin['mass_kg']=np.round(penguin['body_mass_g']/1000)

In [35]:
penguin

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,mass_kg
0,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,male,2007,4.0
1,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,female,2007,4.0
2,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,female,2007,3.0
3,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,male,2007,4.0
4,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,female,2007,3.0
...,...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.80000,19.80000,207.000000,4000.000000,male,2009,4.0
340,Chinstrap,Dream,43.50000,18.10000,202.000000,3400.000000,female,2009,3.0
341,Chinstrap,Dream,49.60000,18.20000,193.000000,3775.000000,male,2009,4.0
342,Chinstrap,Dream,50.80000,19.00000,210.000000,4100.000000,male,2009,4.0
343,Chinstrap,Dream,50.20000,18.70000,198.000000,3775.000000,female,2009,4.0

<h1><strong>Exploring Data Analytics (EDA)</strong></h1>

Questions:
1. Which species has the most females?
2. Which species has the least males?
3. Which species has the longest flipper length?
4.  Which species has the longest bill length?
5.  What is the average bill depth of Gentoo penguins?
6.  What is the average mass_kg of Adelie penguins?
7.  Which sex weighs more on average?
8. In Chinstrap penguins, which is heavier on average, females or males?
9. In Adelie penguins, which sex has the longest flipper?
10. Does sex have an influence on the correlation between  bill length and body mass?
11. How does flipper length correlate with body mass in Adelie penguins?
12. Is there a relationship between body mass and island location for Chinstrap penguins?

<h1><strong>1. Which species has the most females?</strong></h1>
<hr>